version: "3.6"
services:
    mysql:
        image: mysql
        command: 
          - --default-authentication-plugin=mysql_native_password
          - --character-set-server=utf8
          - --collation-server=utf8_general_ci
        environment:
          MYSQL_ROOT_PASSWORD: 'rootpass'
          MYSQL_DATABASE: 'demo'
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'pass'
        ports:
          - "8002:3306"

    webserver:
        build: .
        working_dir: /var/www/html
        volumes:
          - .:/var/www/html
        ports:
          - "8000:80"

